[main]
plugins=keyfile

[ifupdown]
managed=true

[keyfile]
unmanaged-devices=none

[device-all]
match-device=*
managed=1

[device-wifi]
match-device=type:wifi
managed=1

[device-ethernet]
match-device=type:ethernet
managed=1
