[General]
EnableNetworkConfiguration=false
AddressRandomization=disabled
ManagementFrameProtection=0
ControlPortOverNL80211=false
DisableOCV=true

[Rank]
BandModifier2_4GHz=10.0
BandModifier5GHz=0.0
BandModifier6GHz=0.0

[DriverQuirks]
DefaultInterface=iwlwifi
ForcePae=iwlwifi
PowerSaveDisable=iwlwifi
SaeDisable=iwlwifi
